# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'latihan_week2_hari2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'StepSlider'

  # Pods for latihan_week2_hari2

  target 'latihan_week2_hari2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'latihan_week2_hari2UITests' do
    # Pods for testing
  end

end
