# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'projecttugas2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'FloatingPanel'
  pod 'Toast-Swift'
  pod 'lottie-ios'
  pod 'SkeletonView'
  pod 'netfox'
  pod 'FirebaseCore'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
  pod 'SnapKit'
  pod 'ReachabilitySwift'

  # Pods for projecttugas2

  target 'projecttugas2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'projecttugas2UITests' do
    # Pods for testing
  end

end
